- name: variable types
  hosts: localhost
  connection: local
  vars:
    fruit_name: Orange # String
    quantity: 100 # number
    for_sale: true # boolean
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: Fruit Name - {{ fruit_name }}, Quantity - {{ quantity }}
      when: for_sale
